### ISSUE TITLE
Backport 3.0 to Java 17

### ISSUE THREAD

**Issue by antieksi** [I-No-oNe/Glowing-entities#3]
Apparently the 3.0 version does support 1.20.1, but... it doesn't support Java 17. I mean, how do you think this mod should work on 1.20.1 with Java 21?
I'd like to use the mod without having to manually set light level to 15 every time I change dimensions or servers.

**Comment by antieksi** [comment]
To clarify: this is how it does look for me, in the logs.

```
Exception caught from launcher
java.lang.RuntimeException: Error creating Mixin config glowing_entities.client.mixins.json for mod glowing_entities
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:96)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:151)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Caused by: org.spongepowered.asm.launch.MixinInitialisationError: Error initialising mixin config glowing_entities.client.mixins.json
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:153)
	at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:100)
	at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:87)
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:94)
	... 6 more
Caused by: java.lang.IllegalArgumentException: The requested compatibility level JAVA_21 could not be set. Level is not supported by the active JRE or ASM version (Java 17.0, ASM 9.6 (ASM10_EXPERIMENTAL))
	at org.spongepowered.asm.mixin.MixinEnvironment.setCompatibilityLevel(MixinEnvironment.java:1627)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.initCompatibilityLevel(MixinConfig.java:557)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInit(MixinConfig.java:502)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.onLoad(MixinConfig.java:430)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.create(MixinConfig.java:1293)
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:148)
	... 9 more
Exiting with ERROR
```

**Comment by I-No-oNe** [comment]
Which version of glowing entities are you using?
What is the name of the jar?

**Comment by antieksi** [comment]
> Which version of glowing entities are you using? What is the name of the jar?

I've tried to instal the latest version, [glowing-entities-version-3.0-1.21.jar](https://modrinth.com/mod/glowing-entities/version/gUHxwCPc). Currently I'm forced to use [Glowing-Entities-2.0.-1.20.4-1.19.2.jar](https://modrinth.com/mod/glowing-entities/version/2.0).

**Comment by I-No-oNe** [comment]
> > Which version of glowing entities are you using? What is the name of the jar?
> 
> I've tried to instal the latest version, [glowing-entities-version-3.0-1.21.jar](https://modrinth.com/mod/glowing-entities/version/gUHxwCPc). Currently I'm forced to use [Glowing-Entities-2.0.-1.20.4-1.19.2.jar](https://modrinth.com/mod/glowing-entities/version/2.0).

Please open https://modrinth.com/mod/glowing-entities/version/3.0 and download the file named "Glowing-Entities-3.0.-1.20.4-1.19.2.jar"

**Comment by antieksi** [comment]
It seems that I made a typo. Yes, I did download the 1.19.2-1.20.4 version.

**Comment by I-No-oNe** [comment]
![Screenshot_20240828_181648_Chrome](https://github.com/user-attachments/assets/23cacd2c-a1f3-4215-a444-25bb73eb7ed0)
Idk what the problem, please check u r using the right jar file

**Comment by I-No-oNe** [comment]
For now, I'm closing the issue, re open it if u need something
